<template>
    <div class="form">
        <h2 style="text-align: center;">Loan</h2>
        <b-form @register="onCreate">
            <b-form-group class="margins" id="input-group-1" label="Loan-ID:" label-for="input-1">
                <b-form-input id="input-1" v-model="form.id" placeholder="Autogenerated ID"></b-form-input>
            </b-form-group>
            <b-form-group class="margins" id="input-group-2" label="Installment_Plan:" label-for="input-2">
                <b-form-input id="input-2" v-model="form.installmentplan" placeholder="Enter Installment Plan" required></b-form-input>
            </b-form-group>
            <b-form-group class="margins" id="input-group-3" label="Interest_Rate:" label-for="input-3">
                <b-form-input id="input-3" v-model="form.interestrate" placeholder="Enter Interest Rate" required></b-form-input>
            </b-form-group>
            <b-form-group class="margins" id="input-group-4" label="Loan_Amount:" label-for="input-4">
                <b-form-input id="input-4" v-model="form.loanamount" placeholder="Enter Loan Amount" required></b-form-input>
            </b-form-group>
            <label class="margins" for="example-datepicker">Payment Due Date</label>
            <b-form-datepicker id="datepicker" v-model="value" class="mb-2"></b-form-datepicker>

            <b-form-group class="margins" id="input-group-5" label="Customer_Id:" label-for="input-5">
                <b-form-input id="input-5" v-model="form.customerid" placeholder="Enter Customer Id" required></b-form-input>
            </b-form-group>

            <b-form-group class="margins" id="input-group-6" label="Product_Id:" label-for="input-6">
                <b-form-input id="input-6" v-model="form.productid" placeholder="Enter Product Id"
                    required></b-form-input>
            </b-form-group>

            <div class="buttonsAtBottom">
                <b-button class="padding" type="create" variant="primary">Create</b-button>
            </div>

        </b-form>
        <div>
            <h5 style="text-align: center;">Loan Details</h5>
            <b-table class="margins" hover :items="items" :striped="striped" :bordered="bordered"
                :outlined="outlined"></b-table>
        </div>
    </div>
</template>
<script>
export default {

    data() {
        return {
            value: "",
            form: {
                id: '',
                installmentplan: '',
                interestrate: '',
                loanamount: '',
                customerid: '',
                productid: ''
            },
            items: [
                {
                    loanId: '', installmentPlan: '', interestRate: '',
                    loanAmount: '',
                    customerId: '',
                    productId: ''
                }
            ],
            striped: true,
            bordered: true,
            outlined: true
        }
    },
    methods: {
        onCreate() {

        }
    }

}
</script>

<style lang="css" scoped>
.form {
    margin: auto;
    width: 50%;
    border: 2px solid grey;
    padding: 10px;
}

.buttonsAtBottom {
    display: flex;
    margin-top: 10px;
    margin-bottom: 10px;
    justify-content: center;

}

.margins {
    margin: 5px 0px 5px 0px;
}

.padding {
    margin: 1rem;
}
</style>